### ISSUE TITLE
Empty array productIDs

### ISSUE THREAD

**Issue by anvanza** [elgentos/magento2-regenerate-catalog-urls#69]
When not defining any productIds on a command like
bin/magento regenerate:product:url -s13
the output is always 0 urls

On the line below it checks for a null value instead of an empty array
https://github.com/elgentos/magento2-regenerate-catalog-urls/blob/master/src/Service/RegenerateProductUrl.php#L88

**Comment by peterjaap** [comment]
Thanks for the report, could you create a PR with the fix?

**Comment by peterjaap** [comment]
Found the fix myself https://github.com/elgentos/magento2-regenerate-catalog-urls/commit/2ba397dbe3a9f766fa44deb9ee8131611f84ed0b

**Comment by anvanza** [comment]
Thanks @peterjaap !
