### ISSUE TITLE
Bulk product url update not working correctly

### ISSUE THREAD

**Issue by leedyche** [elgentos/magento2-regenerate-catalog-urls#71]
Hi guys,

I have found an issue with the bulk product update command ie running '/bin/magento regenerate:product:url' 

It currently loops through deleting url's and does it essentially one at a time and takes forever. It seems the issue is in RegenerateProductUrl.php line 101, it isnt clearing the deleteUrls array so its always greater than batch size after the first delete. I added this line 

$deleteProducts = []; //reset the array to blank

directly after line 101 and tested it and it solved the issue and helped me fix my live site.

Thanks for the utility it was a great help!

(I dont have access to create a branch otherwise ide have created a PR)

Cheers

Lee

**Comment by peterjaap** [comment]
Good catch, thanks!

https://github.com/elgentos/magento2-regenerate-catalog-urls/compare/0.3.2...0.3.3

New release; https://github.com/elgentos/magento2-regenerate-catalog-urls/releases/tag/0.3.3

**Comment by sprankhub** [comment]
Can we close this? :)

**Comment by peterjaap** [comment]
Yes!
