### ISSUE TITLE
Emulation dependency injected in the console commands through DI, tries to connect to database

### ISSUE THREAD

**Issue by hostep** [elgentos/magento2-regenerate-catalog-urls#76]
Hi!

There is a dependency injected in the console commands of this module that tries to connect to the database.
Since constructors of console commands are executed whenever `bin/magento` is ran, this causes an unneeded db connection attempt every single time.

Steps to reproduce:
- Have a working Magento install (I'm using Magento 2.4.6-p1, but any version will probaby have the same issue)
- Have `elgentos/regenerate-catalog-urls` version 0.3.5 installed
- Change your `app/etc/env.php` file and use a database user that doesn't exist
- Run `bin/magento`

Expected is no error mesages
But we are getting the following at the bottom:

```
In Abstract.php line 144:

  SQLSTATE[HY000] [1045] Access denied for user 'non-existing-user'@'localhost' (using password: YES)


In Abstract.php line 128:

  SQLSTATE[HY000] [1045] Access denied for user 'non-existing-user'@'localhost' (using password: YES)
```

After some quick playing around with the dependencies in the console commands of this module, it turns out that it's the dependency `Magento\Store\Model\App\Emulation` that causes the problem (either directly or through one of it's own dependencies, didn't check further). If I quickly comment out that Emulation dependency in the 3 console commands of this module, then we no longer get that error.

Solution is probably to inject `Magento\Store\Model\App\Emulation` as a Proxy, that should prevent a database connection to be made upon each `bin/magento` call.

(you might need https://github.com/magento/magento2/pull/37424 as well, to fully test if this got fixed)

Thanks for considering this fix! 🙂

**Comment by peterjaap** [comment]
Hi @hostep,

Thanks for reporting this! Unfortunately, I can't seem to be able to replicate this on a 2.4.7-beta1 or 2.4.6-p3 instance. I keep getting the access denied error even without this extension.

But I've taken the liberty to add a `\Proxy` anyway, since it won't break anyway. Could maybe test the latest version to see if it helps?

https://github.com/elgentos/magento2-regenerate-catalog-urls/releases/tag/0.3.6

**Comment by hostep** [comment]
Hey @peterjaap 

Thanks for the effort!
I took a deeper look and found out we needed yet another `\Proxy` to fully fix the problem, the ones you added are needed, but a fourth one is needed as well to fully fix the problem.
Somehow I missed that in the description of this issue.

See #79
