### ISSUE TITLE
0.4.0 doesnt work with single-store mode

### ISSUE THREAD

**Issue by mortenbirkelund** [elgentos/magento2-regenerate-catalog-urls#82]
When trying to regenerate the category urls on a 2.4.7-p4 with single store mode enabled, i get` "Root category with ID 0, was not found."
`
It doesnt matter if i pass a store when running the command or not, the store will allways be 0 and the root category will thereby be 0 (which doesnt exists). 

Store should be 1 and root category should be 2. 

![image](https://github.com/elgentos/magento2-regenerate-catalog-urls/assets/8955039/ab1dd878-b038-4c0b-b3dd-7695e4c1bf03)

This problem happens because 0.4.0 throws an exception if it doesnt find a root category attached to the given store, and 0 is not the correct store. 
https://github.com/marvinhinz/magento2-regenerate-catalog-urls/blob/597f4fabfd4d21eb8fcf66cf9cc31f88b59dee97/src/Console/Command/RegenerateCategoryUrlCommand.php#L116-L119

It happens because 0 is hard coded as the store, in case of Single-store mode, which is not correct. 
https://github.com/marvinhinz/magento2-regenerate-catalog-urls/blob/9abb064ac2d71b6dc81a37482e4aac118ca58d9e/src/Console/Command/AbstractRegenerateCommand.php#L63-L65

![image](https://github.com/elgentos/magento2-regenerate-catalog-urls/assets/8955039/11196b6e-dd9c-46bf-a776-9f8e6db3f535)

An easy solution would just be to change the hardcoded store id from 0 to 1.

**Comment by mortenbirkelund** [comment]
@peterjaap Let me know what you think

**Comment by peterjaap** [comment]
Thanks for noticing this. Tested it locally on a single store instance and found the same. I changed the 0 to a 1 and created a new release; https://github.com/elgentos/magento2-regenerate-catalog-urls/releases/tag/0.4.1
